baseURL = "https://przybyl.io"
languageCode = "pl-pl"
DefaultContentLanguage = "pl"
title = "Przybył.io"
theme = "beautifulhugo"
disqusShortname = "simbaxdotinfo"
googleAnalytics = "UA-35178175-4"
summaryLength = 30

[params]
  subtitle = "Taki sobie blog jakiegoś tam studenta informatyki."
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "02.01.2006"
  commit = false
  rss = true
  comments = true
  gcse = "010217182761278009386:m-vrg4fyhdm"

[blackfriday]
  extensions = []
  extensionsmask = ["backslashLineBreak"]

[Author]
  name = "Mateusz Przybył"
  email = "matt@przybyl.io"
  steam = "simbax"
#  facebook = "username"
#  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "MrSimbax"
#  gitlab = "username"
  twitter = "MrSimbax"
  reddit = "MrSimbax"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
#  instagram = "username"
  youtube = "channel/UCwsnG85hBHMiTJrcaCvZCpg"
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    identifier = "about"
    name = "O mnie"
    url = "page/about/"
    weight = 3

[[menu.main]]
    parent = "about"
    name = "O mnie"
    url = "page/about/"
    weight = 1

[[menu.main]]
    parent = "about"
    name = "Portfolio"
    url = "page/portfolio"
    weight = 2

[[menu.main]]
    parent = "about"
    name = "Kontakt"
    url = "page/contact"
    weight = 3

[[menu.main]]
    name = "Tagi"
    url = "tags"
    weight = 3
